spring:
  application:
    name: spring-security-travel
  datasource:
    url: jdbc:h2:mem:ssia
    username: sa
    password:
  sql:
    init:
      mode: always
  ldap:
    embedded:
      ldif: classpath:server.ldif
      base-dn: dc=springframework,dc=org
      port: 33389
authorization:
  key: SD9cICjl1e
logging:
  level:
    org:
      springframework:
        security: debug