spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taskMan
    username: root
    password: werpipl15
  jpa:
    hibernate:
      ddl-auto: none

logging:
  file:
    path: ./logs/
    name: TaskLog.log
  level:
    root: warn
    org.another.tascman.controller: DEBUG
    org.another.tascman.prog: DEBUG
