spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tasktracker
    username: root
    password: werpipl15
  jpa:
    hibernate:
      ddl-auto: update

