spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_server
    username: root
    password: werpipl15
  jpa:
    hibernate:
      ddl-auto: update


server:
  port: 9000
logging:
  org:
    springframework:
      security: debug


