spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: root
    password: werpipl15
  h2:
    console:
      enabled: true # ????????? ?????? ? ??????? H2 ????? ???????
      path: /h2-console # ???? ? ??????? H2 ? ????????
  sql:
    init:
      mode: always # ???????? ????????????? ????? ? ?????? ??? ??????? ??????????
      schema: classpath:schema.sql # ???? ? SQL-??????? ??? ???????? ?????

  jpa:
    hibernate:
      ddl-auto: update # ?????????????? ?????????? ????? ???? ?????? (create, create-drop, validate, update)
    show-sql: true # ?????????? SQL-??????? ? ???????
    properties:
      hibernate:
        format_sql: true # ??????????? SQL-??????? ??? ?????? ??????????

# ?????????????? ????????? ??? ????????????
  test:
    sql:
      init:
        mode: always
        schema: classpath:test-schema.sql
        data: classpath:test-data.sql

