FROM mysql:latest

#Установка началиных параметров Mysql
ENV MYSQL_ROOT_PASSWORD=werpipl15
ENV MYSQL_DATABASES=mydatabase
ENV MYSQL_USER=userR
ENV MYSQL_PASSWORD=userRpass

#Открытие порта
EXPOSE 9999