spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_token
    username: root
    password: werpipl15
  flyway:
    baseline-on-migrate: true

jwt:
  secret: h13g41312u556k45b654n43532m234kdk2
  lifetime: 30m


logging:
  level:
    root: info


