spring:
  #  RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: werpipl15
  data:
    rest:
      base-path: /api
  application:
    name: new-taco
  datasource:
    url: jdbc:mysql://localhost:3306/taconew
    username: root
    password: werpipl15
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
  boot:
    admin:
      client:
        url: http://localhost:9090
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, loggers, env, beans, httptrace, mapping, threaddump


logging:
  file:
    path: /var/log/
    name: TacoCloud.log
  level:
    root: debug
    org:
      springframework:
        security: info

#Email
#tacocloud:
#  email:
#    host: imap.gmail.com
#    mailbox: INBOX
#    username: wqeqweqweqweqw
#    password: qeqweqweqw
#    poll-rate: 10000






