spring:
  data:
    rest:
      base-path: /api
  application:
    name: new-taco
  datasource:
    url: jdbc:mysql://localhost:3306/taconew
    username: root
    password: werpipl15
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080

logging:
  file:
    path: /var/logs/
    name: TacoCloud.log
  level:
    root: info
    org:
      springframework:
        security: debug
