spring:
  artemis:
    user: artemis
    password: artemis
  jms:
    template:
      default-destination: tacocloud.order.queue
  data:
    rest:
      base-path: /api
  application:
    name: new-taco
  datasource:
    url: jdbc:mysql://localhost:3306/taconew
    username: root
    password: werpipl15
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks



  devtools:
    restart:
      enabled=false:
server:
  port: 8080


logging:
  file:
    path: /var/log/
    name: TacoCloud.log
  level:
    root: debug
    org:
      springframework:
        security: info
        jms: debug




