spring:
  application:
    name: integration-test-studi
  data:
    redis:
      password: werpipl15
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 23123
